// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTask.DataBase;

#nullable disable

namespace SmartTask.DataBase.Migrations
{
    [DbContext(typeof(SmartTaskDbContext))]
    [Migration("20230218093008_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartTask.Models.Entities.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("equipmentType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 800.0,
                            Name = "Technological Machines"
                        },
                        new
                        {
                            Id = 2,
                            Area = 100.0,
                            Name = "Computing Devices"
                        },
                        new
                        {
                            Id = 3,
                            Area = 350.0,
                            Name = "Industrial Furnaces"
                        },
                        new
                        {
                            Id = 4,
                            Area = 50.0,
                            Name = "Equipment for thermal processing of food products"
                        },
                        new
                        {
                            Id = 5,
                            Area = 1000.0,
                            Name = "Machine tools"
                        },
                        new
                        {
                            Id = 6,
                            Area = 750.0,
                            Name = "Aggregate installation"
                        });
                });

            modelBuilder.Entity("SmartTask.Models.Entities.PlacementContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentCount")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PremisesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("PremisesId");

                    b.ToTable("placementContract", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentCount = 2,
                            EquipmentTypeId = 4,
                            PremisesId = 3
                        },
                        new
                        {
                            Id = 2,
                            EquipmentCount = 4,
                            EquipmentTypeId = 2,
                            PremisesId = 5
                        });
                });

            modelBuilder.Entity("SmartTask.Models.Entities.ProductionPremises", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StandartArea")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("productionPremises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warehouse",
                            StandartArea = 2000.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Workshop",
                            StandartArea = 1000.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kitchen",
                            StandartArea = 100.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hangar",
                            StandartArea = 1200.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shed",
                            StandartArea = 500.0
                        });
                });

            modelBuilder.Entity("SmartTask.Models.Entities.PlacementContract", b =>
                {
                    b.HasOne("SmartTask.Models.Entities.EquipmentType", "EquipmentType")
                        .WithMany("Contracts")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartTask.Models.Entities.ProductionPremises", "Premises")
                        .WithMany("Contracts")
                        .HasForeignKey("PremisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("Premises");
                });

            modelBuilder.Entity("SmartTask.Models.Entities.EquipmentType", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("SmartTask.Models.Entities.ProductionPremises", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
